//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacketSniffer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SnifferLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SnifferLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacketSniffer.Resources.SnifferLabels", typeof(SnifferLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack Number.
        /// </summary>
        public static string AckNumber {
            get {
                return ResourceManager.GetString("AckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum.
        /// </summary>
        public static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Port.
        /// </summary>
        public static string DestinationPort {
            get {
                return ResourceManager.GetString("DestinationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACK.
        /// </summary>
        public static string FlagAck {
            get {
                return ResourceManager.GetString("FlagAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN.
        /// </summary>
        public static string FlagFin {
            get {
                return ResourceManager.GetString("FlagFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RST.
        /// </summary>
        public static string FlagRst {
            get {
                return ResourceManager.GetString("FlagRst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYN.
        /// </summary>
        public static string FlagSyn {
            get {
                return ResourceManager.GetString("FlagSyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination IP.
        /// </summary>
        public static string IpDestination {
            get {
                return ResourceManager.GetString("IpDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source IP.
        /// </summary>
        public static string IpSource {
            get {
                return ResourceManager.GetString("IpSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Sniffer.
        /// </summary>
        public static string PacketSnifferTitle {
            get {
                return ResourceManager.GetString("PacketSnifferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :{0} → :{1}.
        /// </summary>
        public static string PortSummary {
            get {
                return ResourceManager.GetString("PortSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string SectionFlags {
            get {
                return ResourceManager.GetString("SectionFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP Header.
        /// </summary>
        public static string SectionIcmpHeader {
            get {
                return ResourceManager.GetString("SectionIcmpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Header.
        /// </summary>
        public static string SectionIpHeader {
            get {
                return ResourceManager.GetString("SectionIpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Error.
        /// </summary>
        public static string SectionSequenceError {
            get {
                return ResourceManager.GetString("SectionSequenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Header.
        /// </summary>
        public static string SectionTcpHeader {
            get {
                return ResourceManager.GetString("SectionTcpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Header.
        /// </summary>
        public static string SectionUdpHeader {
            get {
                return ResourceManager.GetString("SectionUdpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an interface to start capturing packets..
        /// </summary>
        public static string SelectInterfaceFormCardSubtitle {
            get {
                return ResourceManager.GetString("SelectInterfaceFormCardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Interface.
        /// </summary>
        public static string SelectInterfaceFormCardTitle {
            get {
                return ResourceManager.GetString("SelectInterfaceFormCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Port.
        /// </summary>
        public static string SourcePort {
            get {
                return ResourceManager.GetString("SourcePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTL.
        /// </summary>
        public static string Ttl {
            get {
                return ResourceManager.GetString("Ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Code.
        /// </summary>
        public static string TypeCode {
            get {
                return ResourceManager.GetString("TypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}/s | {2}: {3}/s.
        /// </summary>
        public static string UsageSummary {
            get {
                return ResourceManager.GetString("UsageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
    }
}
